import { ArrowLeft, BrainCircuit, CheckCircle2, Clock3, Languages } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { getConversation } from '../modules/conversation-history/conversationHistoryService'
import { TranscriptPanel } from '../components/conversation/TranscriptPanel'

export function ConversationDetailPage() {
  const { id } = useParams(); const conversation = getConversation(id)
  if (!conversation) return <div className="mx-auto max-w-3xl px-5 py-24 text-center"><h1 className="font-display text-3xl font-bold">Conversation not found</h1><Link to="/history" className="btn-primary mt-6">Back to history</Link></div>
  return <div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 sm:py-14"><Link to="/history" className="mb-7 inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-primary"><ArrowLeft size={17}/>Back to history</Link><section className="card mb-5 overflow-hidden"><div className="bg-gradient-to-br from-[#24203d] to-[#403883] p-7 text-white sm:p-9"><div className="mb-4 flex flex-wrap gap-3 text-xs font-bold text-white/75"><span>{conversation.date} · {conversation.time}</span><span className="flex items-center gap-1"><Clock3 size={13}/>{conversation.duration}</span><span className="flex items-center gap-1"><Languages size={13}/>{conversation.sourceLanguage} → {conversation.targetLanguage}</span></div><h1 className="font-display text-2xl font-bold sm:text-3xl">Conversation recap</h1><p className="mt-4 max-w-4xl leading-7 text-white/85">{conversation.summary}</p></div><div className="grid divide-y divide-[#ececf3] p-6 sm:grid-cols-2 sm:divide-x sm:divide-y-0"><div className="sm:pr-6"><h2 className="mb-3 flex items-center gap-2 font-display font-bold"><BrainCircuit size={18} className="text-primary"/>Intent & topics</h2><p className="mb-3 text-sm text-muted">{conversation.intent}</p><div className="flex flex-wrap gap-2">{conversation.topics?.map(topic => <span key={topic} className="rounded-full bg-primary/8 px-3 py-1 text-xs font-bold text-primary">{topic}</span>)}</div></div><div className="pt-6 sm:pl-6 sm:pt-0"><h2 className="mb-3 flex items-center gap-2 font-display font-bold"><CheckCircle2 size={18} className="text-cyan"/>Key points</h2><ul className="space-y-2">{conversation.keyPoints?.map(point => <li key={point} className="flex gap-2 text-sm text-muted"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-cyan"/>{point}</li>)}</ul></div></div></section>
    {conversation.transcript?.length > 0 && <div className="grid gap-5 lg:grid-cols-2"><TranscriptPanel title="Original transcript" subtitle={conversation.sourceLanguage} messages={conversation.transcript}/><TranscriptPanel translated title="Translated text" subtitle={conversation.targetLanguage} messages={conversation.translations || []}/></div>}
  </div>
}
