import { ArrowRight, AudioWaveform, Languages, Mic2, Sparkles, TimerReset } from 'lucide-react'
import { Link } from 'react-router-dom'

const features = [
  { icon: Mic2, title: 'Live transcription', text: 'Capture every word as the conversation unfolds.', color: 'bg-primary/10 text-primary' },
  { icon: Languages, title: 'Instant translation', text: 'Bridge languages naturally, without losing the flow.', color: 'bg-cyan/10 text-cyan' },
  { icon: Sparkles, title: 'Smart summaries', text: 'Walk away with topics, intent, and clear next steps.', color: 'bg-[#fff3dc] text-[#e99b1b]' },
]

export function DashboardPage() {
  return <>
    <section className="relative overflow-hidden"><div className="dot-grid absolute right-0 top-0 h-full w-1/2 opacity-60"/><div className="absolute -right-24 top-12 h-80 w-80 rounded-full bg-cyan/10 blur-3xl"/><div className="absolute left-1/3 top-10 h-64 w-64 rounded-full bg-primary/10 blur-3xl"/>
      <div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1.1fr_.9fr] lg:py-32">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-white px-3.5 py-2 text-xs font-bold text-primary shadow-sm"><span className="h-2 w-2 rounded-full bg-cyan"/>Speak freely. Understand instantly.</div><h1 className="max-w-3xl font-display text-5xl font-extrabold leading-[1.06] tracking-[-0.045em] sm:text-6xl lg:text-7xl">Every voice,<br/><span className="gradient-text">clearly understood.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">Record, transcribe, translate, and summarize conversations in real time—so language never slows down a good idea.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/conversation" className="btn-primary"><Mic2 size={19}/>Start new conversation<ArrowRight size={17}/></Link><Link to="/history" className="btn-secondary"><TimerReset size={19}/>View history</Link></div><div className="mt-8 flex items-center gap-3 text-xs font-semibold text-muted"><div className="flex -space-x-2">{['S','M','A'].map((letter,i) => <span key={letter} className={`grid h-8 w-8 place-items-center rounded-full border-2 border-white text-[10px] font-bold text-white ${['bg-primary','bg-cyan','bg-ink'][i]}`}>{letter}</span>)}</div>Built for conversations that matter</div></div>
        <div className="relative mx-auto hidden w-full max-w-md lg:block"><div className="absolute -left-7 top-16 h-32 w-32 rounded-full border border-primary/10"/><div className="card relative rotate-2 p-5"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-primary text-white"><AudioWaveform/></span><div><p className="font-display font-bold">Live conversation</p><p className="text-xs text-muted">English → Vietnamese</p></div></div><span className="flex items-center gap-1.5 rounded-full bg-red-50 px-3 py-1.5 text-xs font-bold text-red-500"><span className="h-2 w-2 rounded-full bg-red-500"/>REC</span></div><FakeMessage name="Sarah" text="Let’s review the launch plan for next month."/><FakeMessage name="Bản dịch" text="Hãy xem lại kế hoạch ra mắt vào tháng tới." translated/><div className="mt-6 flex h-20 items-center justify-center rounded-2xl bg-[#f7f6ff]"><div className="flex items-center gap-1">{[12,24,18,34,20,28,14,31,22,17,28,11].map((h,i)=><span key={i} className="w-1 rounded-full bg-primary" style={{height:h}}/>)}</div></div></div><div className="card absolute -bottom-8 -left-12 flex -rotate-3 items-center gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan/10 text-cyan"><Sparkles size={18}/></span><div><p className="text-xs font-bold">Summary ready</p><p className="text-[11px] text-muted">3 key points found</p></div></div></div>
      </div>
    </section>
    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="grid gap-4 md:grid-cols-3">{features.map(({icon: Icon,title,text,color}) => <article key={title} className="card p-6 transition hover:-translate-y-1"><span className={`mb-5 grid h-12 w-12 place-items-center rounded-2xl ${color}`}><Icon size={22}/></span><h2 className="font-display text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted">{text}</p></article>)}</div></section>
  </>
}

function FakeMessage({name,text,translated}) { return <div className={`mb-3 max-w-[88%] rounded-2xl p-3.5 ${translated ? 'ml-auto bg-[#ecfafd]' : 'bg-[#f1efff]'}`}><p className={`mb-1 text-[10px] font-bold ${translated ? 'text-cyan' : 'text-primary'}`}>{name}</p><p className="text-xs leading-5">{text}</p></div> }
