import { ArrowRight, CalendarDays, Clock3, Languages, MessageSquareText, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getConversations } from '../modules/conversation-history/conversationHistoryService'

export function HistoryPage() {
  const conversations = getConversations()
  return <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16"><div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">Your library</p><h1 className="font-display text-3xl font-extrabold sm:text-4xl">Conversation history</h1><p className="mt-2 text-muted">Revisit translations, summaries, and decisions from past conversations.</p></div><Link to="/conversation" className="btn-primary"><Plus size={18}/>New conversation</Link></div>
    <div className="grid gap-4">{conversations.map((item, index) => <article key={item.id} className="card group grid gap-5 p-5 transition hover:-translate-y-0.5 hover:border-primary/20 sm:p-6 lg:grid-cols-[170px_1fr_160px] lg:items-center"><div className="flex gap-4 lg:block"><div className="mb-1 flex items-center gap-2 font-bold"><CalendarDays size={16} className="text-primary"/>{item.date}</div><div className="flex items-center gap-2 text-xs text-muted lg:mt-2"><Clock3 size={14}/>{item.time} · {item.duration}</div></div><div className="min-w-0"><div className="mb-3 flex flex-wrap items-center gap-2 text-xs font-bold"><span className="rounded-full bg-primary/8 px-3 py-1 text-primary">{item.sourceLanguage}</span><ArrowRight size={13} className="text-muted"/><span className="rounded-full bg-cyan/10 px-3 py-1 text-[#168ca3]">{item.targetLanguage}</span></div><p className="line-clamp-2 text-sm leading-6 text-muted">{item.summary}</p></div><Link to={`/history/${item.id}`} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#e5e6ee] px-4 py-3 text-sm font-bold transition group-hover:border-primary/30 group-hover:text-primary">View details<ArrowRight size={16}/></Link></article>)}</div>
    {!conversations.length && <div className="card grid min-h-72 place-items-center p-8 text-center"><div><MessageSquareText className="mx-auto mb-4 text-primary" size={36}/><h2 className="font-display text-xl font-bold">No conversations yet</h2><p className="mt-2 text-sm text-muted">Your saved conversations will show up here.</p></div></div>}
  </div>
}
